config/routes.rb
Rails.application.routes.draw do

	root 'home#index'
	resources :jobs, only: [:show, :new, :create, :edit, :update]
	resources :companies, only: [:show, :new, :create, :edit, :update]
  resources :categories, only: [:show, :new, :create]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :jobs
  validates :name, presence: true
end

app/models/company.rb
class Company < ApplicationRecord
	has_many :jobs
  validates :name, presence: true

  def premium?
    jobs.count >= 5
  end
end

app/models/job.rb
class Job < ApplicationRecord
	belongs_to :company
  belongs_to :category
	validates :title, :location, :description, :category, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
    @jobs = @category.jobs
    if @jobs.empty?
      flash.now[:notice] = "Nenhuma vaga disponível"
    end 
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(params.require(:category).permit(:name))
    if @category.save
      redirect_to @category
    else
      flash.now[:notice] = 'Não foi possível criar a categoria'
      render 'new'
    end

  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
	before_action :find_company, only: [:show, :edit, :update]

	def show
		@jobs = @company.jobs
		if @jobs.empty?
			flash.now[:notice] = 'Nenhuma vaga disponível'
		end	
	end

	def new
		@company = Company.new
	end

	def create
		@company = Company.new(company_params)
		if @company.save
			redirect_to @company
		else
			render 'new'			
		end
	end

	def edit
	end

	def update
		if @company.update(company_params)
			redirect_to @company
		else
			flash.now[:notice] = 'Não foi possível atualizar a empresa'
			render 'edit'
		end
	end

	private

	def company_params
		params.require(:company).permit(:name, :location, :mail, :phone)
	end

	def find_company
		@company = Company.find(params[:id])
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@jobs = Job.all
		@companies = Company.all
    @categories = Category.all
	end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
	before_action :set_collections, only: [:new, :edit]
	before_action :find_job, only: [:show, :edit, :update]

	def new
		@job = Job.new
	end

	def create
		@job = Job.new(job_params)
		if @job.save
			redirect_to @job
		else
			set_collections
			flash.now[:notice] = "Não foi possível criar a vaga"
			render 'new'
		end
	end

	def show
	end

	def edit
	end

	def update
		if @job.update(job_params)
			redirect_to @job
		else
			set_collections
			flash.now[:notice] = "Não foi possível atualizar a vaga"
			render 'edit'
		end
	end

	private

	def set_collections
		@companies = Company.all
		@categories = Category.all
	end

	def job_params
		params.require(:job).permit(:title, :location, :category_id, :company_id, :description, :featured)
	end

	def find_job
		@job = Job.find(params[:id])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/new.html.erb
<section>
  <h1>Criar uma categoria</h1>
  <%= form_for @category do |f| %>
    <div class="form-group">
      <%=f.label :name, 'Categoria'%>:
      <%=f.text_field :name, class: 'form-control', placeholder: 'Nome da categoria' %> 
    </div>
    <div>
      <%= link_to 'Voltar', root_path, class: 'btn btn-default' %>
      <%= f.submit 'Criar Categoria', class: 'btn btn-default' %>
    </div>
  <% end %>

</section>

app/views/categories/show.html.erb
<div>
  <h1><%= @category.name %></h1>
  <%= render @jobs%>
</div>
<div>
  <br><%= link_to 'Voltar', root_path, class: "btn btn-default" %>
</div>

app/views/companies/_form.html.erb
<%= form_for @company do |f| %>
  <div class="form-group">
    <%=f.label :name, 'Nome'%>:
    <%=f.text_field :name, class: 'form-control', placeholder: 'Nome da empresa' %> 
  </div>
  <div class="form-group">
    <%=f.label :location, 'Local'%>:
    <%=f.text_field :location, class: 'form-control', placeholder: 'São Paulo, Rio de Janeiro...'%> 
  </div>
  <div class="form-group">
    <%=f.label :mail, 'Email'%>:
    <%=f.text_field :mail, class: 'form-control', placeholder: 'exemplo@exemplo.com.br'%> 
  </div>
  <div class="form-group">
    <%=f.label :phone, 'Telefone'%>:
    <%=f.text_field :phone, class: 'form-control', placeholder: '(xx) xxxxx-xxxx'%> 
  </div>
  <div>
    <%= link_to 'Voltar', root_path, class: 'btn btn-default' %>
    <%= f.submit submit_text, class: 'btn btn-default' %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<section>
  <h1>Editar uma empresa</h1>
  <%= render partial: 'form', locals: {submit_text: 'Atualizar Empresa'} %>
  
</section>

app/views/companies/new.html.erb
<section>
	<h1>Criar uma empresa</h1>
	<%= render partial: 'form', locals: {submit_text: 'Criar Empresa'} %>

</section>

app/views/companies/show.html.erb
<div>
  <%= image_tag 'estrela' if @company.premium? %>
  <h1><%= @company.name %></h1>
  <dl>
    <dt>Localização:</dt>
    <dd> <%= @company.location %></dd>
    <dt>Email:</dt>
    <dd> <%= @company.mail %></dd>
    <dt>Telefone:</dt>
    <dd> <%= @company.phone %></dd>
  </dl>
  <%= link_to 'Editar', edit_company_path, class: "btn btn-default" %>
</div>
<div>
	<%= render @jobs%>
</div>
<div>
  <br><%= link_to 'Voltar', root_path, class: "btn btn-default" %>
</div>

app/views/home/index.html.erb
<nav class="navbar navbar-default">
	<div class="container-fluid">
		<div class="navbar-header">
			<ul class="nav navbar-nav">
				<li><%= link_to "Criar Vagas", new_job_path %></li>
				<li><%= link_to "Criar Empresas", new_company_path %></li>
				<li><%= link_to "Criar Categorias", new_category_path %></li>
			</ul>
		</div>
	</div>
</nav>

<div class="row">
	<div class="col-md-9">
		<section>
			<div class="row">
				<% @jobs.each do |job| %>
					<div class="col-md-6">
						<%= render job%>
					</div>
				<% end %>
			</div>
		</section>
	</div>
	<div class="col-md-3">
		<aside>
			<h3>Empresas</h3>
			<div>
				<% @companies.each do |company| %>
					<%= link_to company.name, company %></br>
				<% end %>
			</div>
			<h3>Categorias</h3>
			<div>
				<% @categories.each do |category| %>
					<%= link_to category.name, category%></br>
				<% end %>
			</div>
		</aside>
	</div>
</div>

app/views/jobs/_form.html.erb
<%= form_for @job do |f| %>
	<div class="form-group">
		<%=f.label :title, 'Título'%>:
		<%=f.text_field :title, class: 'form-control', placeholder: 'Nome do anúncio da vaga'%> 
	</div>
	<div class="form-group">
		<%=f.label :location, 'Local'%>:
		<%=f.text_field :location, class: 'form-control', placeholder: 'São Paulo, Rio de Janeiro...'%> 
	</div>
	<div class="form-group">
		<%=f.label :category_id, 'Categoria'%>:
		<%=f.collection_select(:category_id, @categories, :id, :name, {}, class: 'form-control')%> 
	</div>
	<div class="form-group">
		<%=f.label :company_id, 'Empresa'%>:
		<%= f.collection_select(:company_id, @companies, :id, :name, {}, class: 'form-control') %>
	</div>
	<div class="form-group">
		<%=f.label :description, 'Descrição'%>:
		<%=f.text_field :description, class: 'form-control'%> 
	</div>
	<div class="form-group">
		<%= f.label :featured, 'Destaque' %>
		<%= f.check_box :featured %>
	</div>
	<div>
		<%= link_to 'Voltar', root_path, class: 'btn btn-default' %>
		<%=f.submit submit_text, class: 'btn btn-default' %>
	</div>
<% end %>

app/views/jobs/_job.html.erb
  <h1><%= link_to job.title, job %>
    <% if job.featured? %>
      <strong><%= '(Destaque)' %></strong>
    <% end %>
  </h1>
  <%= job.company.name %><br> 
  <%= job.location %><br>
  <%= job.category.name %><br>

app/views/jobs/edit.html.erb
<section>
	<h1>Editar uma vaga</h1>
	<%= render partial: 'form', locals: {submit_text: 'Atualizar Vaga'} %>
</section>

app/views/jobs/new.html.erb
<section>
	<h1>Criar uma vaga</h1>
	<%= render partial: 'form', locals: {submit_text: 'Criar Vaga'} %>

</section>

app/views/jobs/show.html.erb
<div>
  <dl>
    <dt><h1><%= @job.title %></h1></dt>
    <dd><%= @job.category.name %></dd>
    <dd><%= @job.company.name %></dd>
    <dd><%= @job.description %></dd>
    <dd><%= @job.location %></dd>
  </dl>
	<% if @job.featured? %>
		<strong><%= 'Destaque' %></strong>
	<% end %>
  <%= link_to 'Editar', edit_job_path, class: "btn btn-default" %>
</div>
<div>
  <%= link_to 'Voltar', root_path, class: "btn btn-default" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EmpregoJa</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
  	<header>
  		<h1>Emprego Já</h1>
  	</header>
      <span><%= notice %></span>
      <%= yield %>
    </div> 
  </body>
</html>